version: '3.3'
services:
  db:
    image: mysql:5.7
    env_file:
        - database.env
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - mysql-db:/var/lib/mysql
volumes:
    mysql-db: